<?xml version="1.0" encoding="UTF-8" ?>
<testsuite errors="1" failures="1" tests="3" name="tst_Assert">
  <properties>
    <property value="@INSERT_QT_VERSION_HERE@" name="QTestVersion"/>
    <property value="@INSERT_QT_VERSION_HERE@" name="QtVersion"/>
    <property value="" name="QtBuild"/>
  </properties>
  <testcase result="pass" name="initTestCase"/>
  <testcase result="pass" name="testNumber1"/>
  <testcase result="fail" name="testNumber2">
    <!-- message="ASSERT: &quot;false&quot; in file qtbase/tests/auto/testlib/selftests/assert/tst_assert.cpp, line 53" type="qfatal" -->
    <failure message="Received a fatal error." result="fail"/>
  </testcase>
  <system-err>
<![CDATA[ASSERT: "false" in file qtbase/tests/auto/testlib/selftests/assert/tst_assert.cpp, line 0]]>
  </system-err>
</testsuite>
