##teamcity[testSuiteStarted name='tst_Xunit' flowId='tst_Xunit']
##teamcity[testStarted name='initTestCase()' flowId='tst_Xunit']
##teamcity[testFinished name='initTestCase()' flowId='tst_Xunit']
##teamcity[testStarted name='testFunc1()' flowId='tst_Xunit']
##teamcity[testStdOut name='testFunc1()' out='WARNING |[Loc: qtbase/tests/auto/testlib/selftests/xunit/tst_xunit.cpp(0)|]: just a QWARN() !' flowId='tst_Xunit']
##teamcity[testFinished name='testFunc1()' flowId='tst_Xunit']
##teamcity[testStarted name='testFunc2()' flowId='tst_Xunit']
##teamcity[testFailed name='testFunc2()' message='Failure! |[Loc: qtbase/tests/auto/testlib/selftests/xunit/tst_xunit.cpp(0)|]' details='Compared values are not the same|n Actual (2): 2|n Expected (3): 3' flowId='tst_Xunit']
##teamcity[testStdOut name='testFunc2()' out='QDEBUG: a qDebug() call with comment-ending stuff -->' flowId='tst_Xunit']
##teamcity[testFinished name='testFunc2()' flowId='tst_Xunit']
##teamcity[testIgnored name='testFunc3()' message='skipping this function! |[Loc: qtbase/tests/auto/testlib/selftests/xunit/tst_xunit.cpp(0)|]' flowId='tst_Xunit']
##teamcity[testStarted name='testFunc4()' flowId='tst_Xunit']
##teamcity[testFailed name='testFunc4()' message='Failure! |[Loc: qtbase/tests/auto/testlib/selftests/xunit/tst_xunit.cpp(0)|]' details='a forced failure!' flowId='tst_Xunit']
##teamcity[testFinished name='testFunc4()' flowId='tst_Xunit']
##teamcity[testStarted name='testFunc5()' flowId='tst_Xunit']
##teamcity[testStdOut name='testFunc5()' out='XFAIL |[Loc: qtbase/tests/auto/testlib/selftests/xunit/tst_xunit.cpp(0)|]: this failure is expected' flowId='tst_Xunit']
##teamcity[testFinished name='testFunc5()' flowId='tst_Xunit']
##teamcity[testStarted name='testFunc6()' flowId='tst_Xunit']
##teamcity[testStdOut name='testFunc6()' out='XFAIL |[Loc: qtbase/tests/auto/testlib/selftests/xunit/tst_xunit.cpp(0)|]: this failure is also expected' flowId='tst_Xunit']
##teamcity[testFinished name='testFunc6()' flowId='tst_Xunit']
##teamcity[testStarted name='testFunc7()' flowId='tst_Xunit']
##teamcity[testFailed name='testFunc7()' message='Failure! |[Loc: qtbase/tests/auto/testlib/selftests/xunit/tst_xunit.cpp(0)|]' details='|'true|' returned TRUE unexpectedly. ()' flowId='tst_Xunit']
##teamcity[testFinished name='testFunc7()' flowId='tst_Xunit']
##teamcity[testStarted name='cleanupTestCase()' flowId='tst_Xunit']
##teamcity[testFinished name='cleanupTestCase()' flowId='tst_Xunit']
##teamcity[testSuiteFinished name='tst_Xunit' flowId='tst_Xunit']
