********* Start testing of tst_Exception *********
Config: Using QtTest library
PASS   : tst_Exception::initTestCase()
FAIL!  : tst_Exception::throwException() Caught unhandled exception
   Loc: [qtbase/src/testlib/qtestcase.cpp(0)]
Totals: 1 passed, 1 failed, 0 skipped, 0 blacklisted, 0ms
********* Finished testing of tst_Exception *********
